name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Windows
            os: windows-latest
            artifact_name: win64
  
##          - name: Linux
##            os: ubuntu-latest
##            artifact_name: linux
##          - name: macOS-arm64
##            os: macos-latest
##            artifact_name: macos-arm64
##          - name: macOS-x86_64
##            os: macos-13
##            artifact_name: macos-x86_64
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install OpenBLAS 
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt-get install -y libopenblas-dev liblapacke-dev
          pkg-config openblas --libs

      - name: Install OpenBLAS (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          brew install openblas
          export PKG_CONFIG_PATH=$(brew --prefix)/opt/openblas/lib/pkgconfig:$PKG_CONFIG_PATH          
          pkg-config openblas --libs

      - name: Install OpenBLAS (windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          Invoke-WebRequest -Uri https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.27/OpenBLAS-0.3.27-x64.zip -OutFile OpenBLAS.zip
          Expand-Archive -Path OpenBLAS.zip
          $currentDir = (Get-Location).Path
          $OpenBLASDir = Join-Path -Path $currentDir -ChildPath 'OpenBLAS\bin'
          $env:PATH = "$OpenBLASDir;$env:PATH"

      - name: build
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd linux
          cc bit2.c `pkg-config openblas --libs` -o bit2
          cc tst_edgesvd.c `pkg-config lapacke --libs` -o tst_edgesvd

      - name: build (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          export PKG_CONFIG_PATH=$(brew --prefix)/opt/openblas/lib/pkgconfig:$PKG_CONFIG_PATH          
          cd macos
          cc -v
          cc `pkg-config openblas --cflags` bit2.c `pkg-config openblas --libs` -o bit2
          cc `pkg-config openblas --cflags` tst_edgesvd.c `pkg-config openblas --libs` -o tst_edgesvd

      - name: build (windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        shell: cmd
        run: |
          cmake -S . -B build -D OPENBLAS_DIR=OpenBLAS
          cmake --build build

      ##- name: Archive production artifacts
      ##  if: ${{ startsWith(matrix.os, 'macos-') }}
      ##  uses: actions/upload-artifact@v4
      ##  with:
      ##    name: openblas-${{ matrix.artifact_name }}
      ##    path: /opt/homebrew/opt/openblas/include/*

      - name: run
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd linux
          ./bit2 isamax 20 1
          ./bit2 info
          ./tst_edgesvd

      - name: run (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          cd macos
          ./bit2 isamax 20 1
          ./bit2 info
          ./tst_edgesvd

      - name: run (windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          cd build
          ctest -C Debug
