name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            artifact_name: linux
          - name: macOS-arm64
            os: macos-latest
            artifact_name: macos-arm64
  
##          - name: macOS-x86_64
##            os: macos-13
##            artifact_name: macos-x86_64
##          - name: Windows
##            os: windows-latest
##            artifact_name: win64
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install OpenBLAS 
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt-get install -y libopenblas-dev liblapacke-dev
          pkg-config openblas --libs

      - name: Install OpenBLAS (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          brew install libopenblas
          pkg-config openblas --libs

      - name: build
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd linux
          cc bit2.c `pkg-config openblas --libs` -o bit2

      - name: build (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          cd macos
          cc bit2.c `pkg-config openblas --libs` -o bit2

      - name: run
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd linux
          ./bit2 isamax 20 1

      - name: run
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          cd macos
          ./bit2 isamax 20 1
