name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            artifact_name: linux
          - name: macOS-arm64
            os: macos-latest
            artifact_name: macos-arm64
          - name: Windows
            os: windows-latest
            artifact_name: win64  

##          - name: macOS-x86_64
##            os: macos-13
##            artifact_name: macos-x86_64
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install OpenBLAS 
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt-get install -y libopenblas-dev liblapacke-dev

      - name: Install OpenBLAS (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          brew install openblas

      - name: Install OpenBLAS (windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          Invoke-WebRequest -Uri https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.27/OpenBLAS-0.3.27-x64.zip -OutFile openblas.zip
          Expand-Archive -Path openblas.zip

      - name: build
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cmake -S . -B build
          cmake --build build

      - name: build (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          export PKG_CONFIG_PATH=$(brew --prefix)/opt/openblas/lib/pkgconfig:$PKG_CONFIG_PATH          
          cmake -S . -B build
          cmake --build build

      - name: build (windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          $currentDir = (Get-Location).Path
          $OpenBLAS_DIR = Join-Path -Path $currentDir -ChildPath 'openblas'
          $env:OpenBLAS_DIR = $OpenBLAS_DIR
          cmake -S . -B build
          cmake --build build

      - name: run
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd build
          ctest
          cat Testing/Temporary/LastTest.log

      - name: run (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          cd build
          ctest
          cat Testing/Temporary/LastTest.log

      - name: run (windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          $currentDir = (Get-Location).Path
          $OpenBLAS_DIR = Join-Path -Path $currentDir -ChildPath 'openblas'
          $env:PATH = "$OpenBLAS_DIR/bin;$env:PATH"
          cd build
          ctest -C Debug
          type Testing/Temporary/LastTest.log
