name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: macOS-arm64
            os: macos-latest
            artifact_name: macos-arm64
  
##          - name: Linux
##            os: ubuntu-latest
##            artifact_name: linux
##          - name: macOS-x86_64
##            os: macos-13
##            artifact_name: macos-x86_64
##          - name: Windows
##            os: windows-latest
##            artifact_name: win64
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install OpenBLAS 
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt-get install -y libopenblas-dev liblapacke-dev
          pkg-config openblas --libs

      - name: Install OpenBLAS (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          brew install openblas
          export PKG_CONFIG_PATH=$(brew --prefix)/opt/openblas/lib/pkgconfig:$PKG_CONFIG_PATH          
          pkg-config openblas --libs

      - name: build
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd linux
          cc bit2.c `pkg-config openblas --libs` -o bit2

      - name: build (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          export PKG_CONFIG_PATH=$(brew --prefix)/opt/openblas/lib/pkgconfig:$PKG_CONFIG_PATH          
          cd macos
          cc `pkg-config openblas --cflags` bit2.c `pkg-config openblas --libs` -o bit2

      - name: Archive production artifacts
        if: ${{ startsWith(matrix.os, 'macos-') }}
        uses: actions/upload-artifact@v4
        with:
          name: openblas-${{ matrix.artifact_name }}
          path: /opt/homebrew/opt/openblas/include/*

      - name: run
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd linux
          ./bit2 isamax 20 1

      - name: run (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          cd macos
          ./bit2 isamax 20 1
          ./bit2 info
